(source "gnu" "http://elpa.emacs-china.org/gnu/")
(source "melpa" "http://elpa.emacs-china.org/melpa/")

(depends-on "auctex")
(depends-on "auctex-latexmk")
(depends-on "company")
(depends-on "exec-path-from-shell")
(depends-on "helm")
(depends-on "helm-swoop")
(depends-on "leuven-theme")
(depends-on "magit")
(depends-on "monokai-theme")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "powerline")
(depends-on "smartparens")
